version: '2'

services:
  datas:
    build: ./datas/
    container_name: datas
    volumes:
      - ./www/test/:/var/www/html/
    tty: true

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "3000:3000"
    container_name: nginx
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - fpm-network

  fpm:
    restart: always
    build: ./php-fpm/
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes_from:
      - datas:rw
    volumes:
      - ./logs/php:/var/log/php
    networks:
      - fpm-network

networks:
  fpm-network: